### ISSUE TITLE
ModuleNotFoundError: No module named 'steampy'

### ISSUE THREAD

**Issue by rakzoser** [YESW0RLD/BuyOrderBot#1]
`
Traceback (most recent call last):
  File "buy_order_bot.py", line 1, in <module>
    from steampy.client import SteamClient
ModuleNotFoundError: No module named 'steampy'
`
I have installed steampy library - `
Requirement already satisfied: steampy in /home/rakzo/.local/lib/python3.12/site-packages (1.0.3)
Requirement already satisfied: requests in /home/rakzo/.local/lib/python3.12/site-packages (from steampy) (2.31.0)
Requirement already satisfied: beautifulsoup4 in /home/rakzo/.local/lib/python3.12/site-packages (from steampy) (4.12.2)
Requirement already satisfied: rsa in /home/rakzo/.local/lib/python3.12/site-packages (from steampy) (4.9)
Requirement already satisfied: soupsieve>1.2 in /home/rakzo/.local/lib/python3.12/site-packages (from beautifulsoup4->steampy) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/rakzo/.local/lib/python3.12/site-packages (from requests->steampy) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /home/rakzo/.local/lib/python3.12/site-packages (from requests->steampy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/rakzo/.local/lib/python3.12/site-packages (from requests->steampy) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /home/rakzo/.local/lib/python3.12/site-packages (from requests->steampy) (2023.7.22)
Requirement already satisfied: pyasn1>=0.1.3 in /home/rakzo/.local/lib/python3.12/site-packages (from rsa->steampy) (0.5.0)
`

**Comment by woctezuma** [comment]
```
pip install steampy
```
